version: '2'
services:
  ihiwmanagement-mysql:
    image: mariadb:10.5
    # volumes:
    #     - ~/volumes/jhipster/ihiwManagement/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ihiwmanagement
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
